### ISSUE TITLE
Provide a user friendly error if a runtime is not installed

### ISSUE THREAD

**Issue by scothis** [projectriff/cli#75]
If a user run`riff knative deployer create` in a cluster that does not have the knative runtime installed, the deployer is created, but the user receives no feedback. Running `riff knative deployer list` says the status is perpetually `Unknown`.

**Comment by ekcasey** [comment]
@scothis Due to the restructuring of the riff deployment, now running either `riff knative deployer create` or `riff knative deployer list` in a cluster w/o the knative runtime installed will result in the following error:
```
Error executing command:
  the server could not find the requested resource (get deployers.knative.projectriff.io)
```

This seems like a significant improvement over the described behavior, but it doesn't immediately point users at the solution to their problem (installing the missing runtime).

Is this error friendly enough for v0.5.0 or do we want to be even more specific? If we want to be more specific what should we use as the criteria for "uninstalled" (e.g. missing all CRDs?)?
